// TLV8 record framing. The whole access-code feature rests on these three
// bytes being right, so the expectations below are hand-written from the
// format documented in src/tlv8.js ([type][length][data]) rather than
// generated by the code under test.

import { test } from "node:test";
import assert from "node:assert/strict";
import {
  tlv8Record,
  DeviceAccessTlv8SubType,
  TxCommand,
} from "../src/tlv8.js";

test("tlv8Record frames type, length, then data", () => {
  const record = tlv8Record(0x02, Buffer.from([0xaa, 0xbb, 0xcc]));
  assert.deepEqual([...record], [0x02, 0x03, 0xaa, 0xbb, 0xcc]);
});

test("tlv8Record writes a zero length for empty data", () => {
  assert.deepEqual([...tlv8Record(0x05, Buffer.alloc(0))], [0x05, 0x00]);
});

test("tlv8Record length byte reflects actual data length, not capacity", () => {
  const record = tlv8Record(0x00, Buffer.from("hello", "utf8"));
  assert.equal(record[1], 5);
  assert.equal(record.length, 7);
});

test("tlv8Record masks a type byte above 0xff", () => {
  // 0x101 & 0xff === 0x01 - documented masking behaviour, not an accident.
  assert.equal(tlv8Record(0x101, Buffer.alloc(0))[0], 0x01);
});

test("tlv8Record accepts exactly 255 bytes of data", () => {
  const record = tlv8Record(0x01, Buffer.alloc(255, 0x7f));
  assert.equal(record[1], 255);
  assert.equal(record.length, 257);
});

test("tlv8Record rejects data longer than one length byte can describe", () => {
  assert.throws(
    () => tlv8Record(0x01, Buffer.alloc(256)),
    /too long \(256 bytes, max 255\)/
  );
});

// These byte values are the wire contract with Kwikset's service, taken from
// the decompiled app's enums. A silent edit here would break real locks, so
// pin them.
test("DeviceAccessTlv8SubType byte values are pinned", () => {
  assert.deepEqual({ ...DeviceAccessTlv8SubType }, {
    AccessCode: 0,
    Schedule: 1,
    FriendlyName: 2,
    ProxyAuthorization: 8,
    BiometricProfile: 16,
  });
});

test("TxCommand byte values are pinned", () => {
  assert.deepEqual({ ...TxCommand }, {
    SetAccessCode: 4,
    DeleteDeviceAccess: 5,
    DeleteAllAccessCodes: 10,
    AccessCodeReadSettings: 32,
    EditAccessCode: 113,
  });
});

test("the subtype and command enums are frozen", () => {
  assert.ok(Object.isFrozen(DeviceAccessTlv8SubType));
  assert.ok(Object.isFrozen(TxCommand));
});
